/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Teste.RelatorioSupervisor;

import classes.EResultado;
import classes.Exame;
import dao.DAOExame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class RelatorioSupervisor extends javax.swing.JDialog {

    private ArrayList<Exame> exames;
    private String data;
    
    /**
     * Creates new form RelatorioSupervisor
     */
    public RelatorioSupervisor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        microscopio = new javax.swing.JLabel();
        duGustinClinicas = new javax.swing.JLabel();
        preto = new javax.swing.JPanel();
        dia = new javax.swing.JLabel();
        pacientesAtendidos = new javax.swing.JLabel();
        detectados = new javax.swing.JLabel();
        naoDetectados = new javax.swing.JLabel();
        foraDoPrazo = new javax.swing.JLabel();
        poucoMaterial = new javax.swing.JLabel();
        inconclusivo = new javax.swing.JLabel();
        invalido = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(917, 870));

        microscopio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/microscopio (1).png"))); // NOI18N

        duGustinClinicas.setBackground(new java.awt.Color(0, 0, 0));
        duGustinClinicas.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        duGustinClinicas.setText("DU GUSTIN CLÍNICAS");
        duGustinClinicas.setToolTipText("");

        preto.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pretoLayout = new javax.swing.GroupLayout(preto);
        preto.setLayout(pretoLayout);
        pretoLayout.setHorizontalGroup(
            pretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pretoLayout.setVerticalGroup(
            pretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dia.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        dia.setText("Relatório Diário: XXXX-XX-XX");

        pacientesAtendidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacientesAtendidos.setText("Número de Pacientes Atendidos:");

        detectados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        detectados.setText("XX Exames Detectados");

        naoDetectados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        naoDetectados.setText("XX Exames Não Detectados");

        foraDoPrazo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foraDoPrazo.setText("XX Pacientes para Recoleta, Motivo: Amostra Fora do Prazo (24h);");

        poucoMaterial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        poucoMaterial.setText("XX Pacientes para Recoleta, Motivo: Pouco Material Coletado;");

        inconclusivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inconclusivo.setText("XX Pacientes com exames inconclusivos e os testes foram refeitos.");

        invalido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invalido.setText("XX Exames Inválidos");

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Assinatura do Responsável");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(microscopio)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(duGustinClinicas)
                                .addGap(0, 279, Short.MAX_VALUE))
                            .addComponent(preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(dia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pacientesAtendidos)
                                    .addComponent(detectados)
                                    .addComponent(naoDetectados)
                                    .addComponent(foraDoPrazo)
                                    .addComponent(poucoMaterial)
                                    .addComponent(inconclusivo)
                                    .addComponent(invalido))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(duGustinClinicas)
                        .addGap(18, 18, 18)
                        .addComponent(preto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(microscopio))
                .addGap(18, 18, 18)
                .addComponent(dia)
                .addGap(40, 40, 40)
                .addComponent(pacientesAtendidos)
                .addGap(18, 18, 18)
                .addComponent(detectados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(naoDetectados)
                .addGap(31, 31, 31)
                .addComponent(foraDoPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(poucoMaterial)
                .addGap(18, 18, 18)
                .addComponent(inconclusivo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(invalido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioSupervisor dialog = new RelatorioSupervisor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detectados;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel duGustinClinicas;
    private javax.swing.JLabel foraDoPrazo;
    private javax.swing.JLabel inconclusivo;
    private javax.swing.JLabel invalido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel microscopio;
    private javax.swing.JLabel naoDetectados;
    private javax.swing.JLabel pacientesAtendidos;
    private javax.swing.JLabel poucoMaterial;
    private javax.swing.JPanel preto;
    // End of variables declaration//GEN-END:variables

    public void prepara(String dia){
        try {
            
            exames = new DAOExame().dia(dia);
            
            data = dia;
            
            preencheLabels();
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Problema de conexão com o SQL");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Problema no driver");
        }
    }
    
    private void preencheLabels(){
        
        DAOExame daoe = new DAOExame();
        try{
            dia.setText("Relatório Diário: " + data);
            pacientesAtendidos.setText("Número de Pacientes Atendidos: " + daoe.numPacientesAtendidos(data));
            detectados.setText(daoe.selectResultado("DETECTADO", data) + " Exames Detectados");
            naoDetectados.setText(daoe.selectResultado("NAO_DETECTADO", data) + " Exames Não Detectados");
            foraDoPrazo.setText(daoe.selectResultado("RECOLETA", data) + " Pacientes para Recoleta, Motivo: Amostra Fora do Prazo (24h)");
            poucoMaterial.setText(daoe.selectResultado("RECOLETA", data) + " Pacientes para Recoleta, Motivo: Pouco Material Coletado");
            inconclusivo.setText(daoe.selectResultado("INCONCLUSIVO", data) + " Pacientes com Exames Inconclusivos");
            invalido.setText(daoe.selectResultado("INVALIDO", data) + " Exames Inválidos");
            
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Problema de conexão com o SQL");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Problema no driver");
        }
        
    }

}
